/run/initialize              #
/vis/open OGL             #打开OGL
/vis/viewer/set/viewpointVector 1 1 1       #正视于 向量1 0 0 
/vis/viewer/set/lightsVector -1 0 0         #光方向
/vis/drawVolume                             #画出体积
/vis/viewer/set/autoRefresh false            #自动刷新 
/vis/scene/add/trajectories smooth          #轨迹平滑
/vis/scene/add/axes 0 0 0 0.5              #添加坐标轴
/vis/scene/add/scale 5 cm
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate      #总计
#/vis/geometry/set/visibility World 0 false   #设置世界不可见
/vis/geometry/set/visibility Room 0 false   #设置Room不可见
/vis/geometry/set/visibility Layer 0 false   #设置Layer不可见



#/vis/viewer/set/style cloud
#/vis/viewer/set/auxiliaryEdge true
#/vis/viewer/set/lineSegmentsPerCircle 100
/vis/geometry/set/colour DriftChamber  1 0 1 1 0.3   #浅蓝色
/vis/geometry/set/colour SupportPlate 1 0 0 0  
/vis/geometry/set/colour Transfor  1 1 0 0 
/vis/geometry/set/colour windows  1 0 0 0        #漂移层 red green blue 透明度
/vis/geometry/set/colour World 1 1 1 1 0.3         #世界
/vis/viewer/set/style surface
#/vis/viewer/set/style surface mesh
